name: Test workflow

on:
  workflow_call:
    inputs:
      dry_run:
        description: "true の場合は対象リポジトリを表示して終了する"
        required: false
        type: string
        default: true
      excluded_repos:
        description: "条件によらず処理対象から除外するリポジトリのリスト"
        required: false
        type: string
        default: '[]'

jobs:
  get_archive_candidates:
    runs-on: ubuntu-latest
    outputs:
      has_old_repos: ${{ steps.get_archive_candidates.outputs.has_old_repos }}
      old_repos: ${{ steps.get_archive_candidates.outputs.old_repos }}

    steps:
      - name: Create output
        id: get_archive_candidates
        run: |
          echo "old_repos=["foo", "bar", "baz"]" >> $GITHUB_OUTPUT
          echo "has_old_repos=true" >> $GITHUB_OUTPUT
          
      - name: Echo if dry run
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo "dry run true"

  create_issues:
    runs-on: ubuntu-latest
    needs: get_archive_candidates
    if: ${{ (needs.get_archive_candidates.outputs.has_old_repos == 'true') && (inputs.dry_run == 'false') }}

    env:
      old_repos: ${{ needs.get_archive_candidates.outputs.old_repos }}

    steps:
      - name: Echo
        run: echo ${{ env.old_repos }}
