name: Create Issue for Archive Candidate Repositories

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      get_repos_inactive_for_months:
        description: "指定された月数以上更新されていないリポジトリのみを対象とする（0 に設定するとすべてのリポジトリが対象となる）"
        required: false
        type: string
        default: "0"

permissions:
  actions: read
  contents: read
  id-token: write
  issues: write

env:
  my_team: sre  # team who has an ownership of parent issue

jobs:
  construct_issue_title_and_body:
    runs-on: ubuntu-latest
    outputs:
      parent_issue_title: ${{ steps.construct_issue_data.outputs.parent_issue_title }}
      parent_issue_body: ${{ steps.construct_issue_data.outputs.parent_issue_body }}
      child_issue_title: ${{ steps.construct_issue_data.outputs.child_issue_title }}
      child_issue_body: ${{ steps.construct_issue_data.outputs.child_issue_body }}
      access_token: ${{ steps.generate_token.outputs.token }}

    steps:
      - name: Set date variable
        id: date
        run: |
          echo "month_ago=$(date -d '-${{ inputs.get_repos_inactive_for_months }} month' --utc +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "current_year=$(date +'%Y')" >> $GITHUB_ENV
          echo "current_quarter=$((($(date +%m)-1)/3+1))Q" >> $GITHUB_ENV
    
      - name: Construct issue title and body
        id: construct_issue_data
        run: |
          echo "parent_issue_title=\"[${{ env.current_year }} ${{ env.current_quarter }}] リポジトリ棚卸し\"" >> "$GITHUB_OUTPUT"
          echo "parent_issue_body=下記は直近 ${{ inputs.get_repos_inactive_for_months }} か月間で更新のないリポジトリのリストです。アーカイブを検討してください。" >> "$GITHUB_OUTPUT"
          echo "child_issue_title=\"[${{ env.current_year }} ${{ env.current_quarter }}] 本リポジトリのアーカイブを検討する\"" >> "$GITHUB_OUTPUT"
          echo "child_issue_body=本リポジトリは直近 ${{ inputs.get_repos_inactive_for_months }} か月間で更新がないようです。利用状況を確認し、アーカイブ可能な場合には @${{ github.event.repository.name }}/${{ env.my_team }} にご連絡ください。" >> "$GITHUB_OUTPUT"

  create_issues_for_organization_repository:
    needs: construct_issue_title_and_body
    uses: ./.github/workflows/_create-issue-at-org-repositories.yml
    with:
      parent_issue_title: ${{ needs.construct_issue_title_and_body.outputs.parent_issue_title }}
      parent_issue_body: ${{ needs.construct_issue_title_and_body.outputs.parent_issue_body }}
      child_issue_title: ${{ needs.construct_issue_title_and_body.outputs.child_issue_title }}
      child_issue_body: ${{ needs.construct_issue_title_and_body.outputs.child_issue_body }}
      get_repos_inactive_for_months: ${{ inputs.get_repos_inactive_for_months }}
    secrets:
      PRIVATE_KEY_ISSUE_CREATOR: ${{ secrets.PRIVATE_KEY_ISSUE_CREATOR }}
